services:
  sguscheduleapns.devicesmanager:
    image: sguscheduleapns.devicesmanager
    build:
      context: .
      dockerfile: SguScheduleAPNs.DevicesManager/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DeviceManagerDatabase;Username=scheduleuser;Password=qWbYhFF6
      - ASPNETCORE_URLS=https://+:5341;http://+:5340
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourCertPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5341:5341"
      - "5340:5340"
    volumes:
      - ./https:/https:ro
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: DeviceManagerDatabase
      POSTGRES_USER: scheduleuser
      POSTGRES_PASSWORD: qWbYhFF6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  postgres_data: