services:
  sguscheduleapns.devicesmanager:
    image: sguscheduleapns.devicesmanager
    build:
      context: .
      dockerfile: SguScheduleAPNs.DevicesManager/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ASPNETCORE_URLS=https://+:5341;http://+:5340
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5341:5341"
      - "5340:5340"
    volumes:
      - ./https:/https:ro
    depends_on:
      - db
  
  sguscheduleapns.notificationserver:
    image: sguscheduleapns.notificationserver
    build:
      context: .
      dockerfile: SguScheduleAPNs.NotificationServer/Dockerfile
    environment:
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_BUNDLE_ID=${APNS_BUNDLE_ID}
      - APNS_KEY_PATH=${APNS_KEY_PATH}
      - DEVICE_MANAGER_BASE_ADDRESS=${DEVICE_MANAGER_BASE_ADDRESS}
    ports:
      - "5441:5441"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  postgres_data: