services:
  devicesmanager:
    image: devicesmanager
    build:
      context: .
      dockerfile: SguScheduleAPNs.DevicesManager/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ASPNETCORE_URLS=http://+:5341;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5341:5341"
    volumes:
      - ./https:/https:ro
    depends_on:
      - db
  
  notificationserver:
    image: notificationserver
    build:
      context: .
      dockerfile: SguScheduleAPNs.NotificationServer/Dockerfile
    environment:
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_BUNDLE_ID=${APNS_BUNDLE_ID}
      - APNS_KEY_PATH=${APNS_KEY_PATH}
      - APNS_KEY_PROD_PATH=${APNS_KEY_PROD_PATH}
      - DEVICE_MANAGER_BASE_ADDRESS=${DEVICE_MANAGER_BASE_ADDRESS}
      - ASPNETCORE_URLS=http://+:5441;
    ports:
      - "5441:5441"
    volumes:
      - ./SguScheduleAPNs.NotificationServer/Secrets:/secrets:ro
      - ./SguScheduleAPNs.NotificationServer/Data:/data

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  postgres_data: